version: '3.8'

services:
  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minio-client:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      sh -c "
        sleep 5;
        mc alias set local http://minio:9000 minio minio123;
        mc mb -p local/mybucket || true;
        exit 0;
      "

  web:
    build: ./web
    volumes:
      - shared-data:/data
      - ./web:/app
    ports:
      - "8080:5000"
    environment:
      - DATA_DIR=/data
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=mybucket
      - S3_ACCESS_KEY=minio
      - S3_SECRET_KEY=minio123

  s3sync:
    image: rclone/rclone
    depends_on:
      - minio
    volumes:
      - shared-data:/data
      - ./rclone.conf:/config/rclone/rclone.conf:ro
    entrypoint: >
      sh -c "
        while true; do
          echo 'Syncing to MinIO...';
          rclone move /data remote:mybucket --config /config/rclone/rclone.conf;
          sleep 30;
        done
      "

volumes:
  shared-data:
  minio-data: